#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu May  9 21:46:26 2019

@author: vrsreeganesh
"""
#status : successful

# docking station
import os
from scipy.io import loadmat

os.system('clear')
#code begins

load_whale_true = loadmat('training_true.mat')
true_matrix = load_whale_true['f_mat']

load_whale_false = loadmat('training_false.mat')
false_matrix = load_whale_false['f_mat']